# Generated by Django 5.0.3 on 2024-04-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('3', 'Low'), ('2', 'Medium'), ('1', 'High'), ('0', 'Not Specified')], default='0', max_length=20),
        ),
    ]
